application:
  subdomain: tduck
  background_task: true
  multi_instance: false
  public_path:
    - /
  upstreams:
    - location: /
      backend: http://tduck-platform:8999/
services:
  mysql:
    # upstream: mysql:8.0.46
    image: registry.lazycat.cloud/czyt/library/mysql:ba7e2aa0a5ad97c0
    environment:
      - MYSQL_ROOT_PASSWORD={{ stable_secret "mysql_password" }}
      - MYSQL_DATABASE=tduck
      - MYSQL_ROOT_HOST=%
      - TZ=Asia/Shanghai
    command: --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    binds:
      - /lzcapp/var/db:/var/lib/mysql
      - /lzcapp/pkg/content:/docker-entrypoint-initdb.d
    healthcheck:
      test:
        - CMD-SHELL
        - mysqladmin ping -h localhost
      start_period: 5m30s
  tduck-platform:
    # upstream: tduckcloud/tduck-platform:latest@sha256:0560d2fbb28d6bd65ff9c96d9e44f22199161e10cf28fb377566da2caa1fc250
    image: registry.lazycat.cloud/czyt/tduckcloud/tduck-platform:25a2981a36d8e697
    environment:
      - JAVA_OPTS=-Duser.language=zh -XX:+UseG1GC
      - TZ=Asia/Shanghai
      - spring.datasource.url=jdbc:mysql://mysql:3306/tduck?useSSL=false&useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&tinyInt1isBit=false&allowPublicKeyRetrieval=true
      - spring.datasource.username=root
      - spring.datasource.password={{ stable_secret "mysql_password" }}
    depends_on:
      - mysql
    binds:
      - /lzcapp/var/upload:/application/BOOT-INF/lib/upload
